---
- hosts: all
  become: true
  tasks:
    - name: Get Git Version
      shell: git --version
      register: gitVersion
      ignore_errors: yes
    - name: Display Message Wheather Git is Installed or Not??
      when: gitVersion.stdout == ""
      debug:
        msg: "Git is not installed"
    - name: Installing Git
      when: gitVersion.stdout == ""
      yum:
        name: git
        state: present
    - name: Get Git Version
      shell: git --version
      register: gitVersion
    - name: Display Git Version
      when: gitVersion.stdout != ""
      debug:
        msg: "Git is installed and version is {{gitVersion.stdout}}"
...