---
- hosts: all
  become: true
  tasks:
   - name: Installing Apache HTTP service
     yum:
      name: httpd
      state: latest
   - name: Copy index.html
     copy:
      src: index.html
      dest: /var/www/html/index.html
   - name: Start HTTP service
     service:
      name: httpd
      state: started
      enabled: true
...
