---
- hosts: all
  become: true
  tasks:
    - name: Install list of packages
      yum: name="{{items}}" state=present
      with_items:
        - git
        - httpd
        - tree
        - wget
        - zip
        - unzip
...